### PR TITLE
move patches from this project to hts-engine to separate source file

### PR DESCRIPTION
**Pull request by glensc**
this moves changes made by this project to hts_engine_API to separate source file.
compared with hts_engine_API-1.10 sourcecode.

the change makes sourcecode better maintainable and easier to upgrade the bundled hts_engine_API to newer version. also probably could help moving the patched code outside the library.

also makes easier for distribution maintainers to link this software with pre-packaged hts_engine api library.

also as the file was new, took the liberty to reformat the sourcefile using hts_engine_API code style (indent with 3 spaces).

### CODE REVIEW

**Comment by ikiissel** [comment]
Good point, thanks

**Comment by glensc** [comment]
err? wtf? why you close? merge it!

**Comment by glensc** [comment]
also your commit messages are REALLY REALLY POOR

https://github.com/ikiissel/synthts_et/commits/master

you should not use git as ftp client....

here's some reading http://chris.beams.io/posts/git-commit/

**Comment by glensc** [comment]
i see you have done something manually there, which causes this merge request to be not able to merge cleanly.

to be actually use the "merge" button in github, you need to remove your previous commit 8e75cb007ef2d0906744dca56750cc005e8f82f3

```
git checkout master
git reset --hard 10a7776
git push -f
```

then the merge button will appear back without complaining about commits.

let me know if you need more guidance, or speaking in Estonian instead ;)

**Comment by ikiissel** [comment]
Dont even know if commenting on github in english is essential. This will stay my very single project for a long time and, yes i use github as ftp. Why i shouldnt :) But thanks for those pull-requests anyway.

**Comment by glensc** [comment]
commit messages are essential when trying to find reasoning behind the commit contents. even for yourself.

**Comment by Kaljurand** [comment]
Git is essentially about human-to-human communication. A sequence of hyphens is not a meaningful/useful sentence in any natural language. The problem with hyphens is also that they are difficult to click on, e.g. I fail at least every second time I try. (I use clicking on the commit message to see the change set, I guess I could start using GitHub's keyboard shortcuts, if you insist on sticking with the hyphen convention. ;))

I'd also prefer if this project followed http://chris.beams.io/posts/git-commit/. I'm monitoring every commit in this project, so the adoption of these guidelines would save me some time and improve my understanding of what is going on.

**Comment by ikiissel** [comment]
Im so sorry. I really didnt expect anybody to be interested in this project nor contribute to it. Im maintaining this project almost alone so there hasnt been any need to cooperative dids :) i promise to improve my git-ing skills.

**Comment by glensc** [comment]
the commit messages can be useful not just other collabrators, but future selves :)

> The contributors to these repositories know that a well-crafted git commit message is the best way to communicate context about a change to fellow developers (and indeed to their future selves). A diff will tell you what changed, but only the commit message can properly tell you why.

**Pull request merged**
